apiVersion: v1
kind: Service
metadata:
  name: devops-sample-service
spec:
  selector:
    app: devops-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
